"""update doctor model

Revision ID: 2a8d8e0bcf82
Revises: 2fc9daf0bb42
Create Date: 2025-07-10 14:49:08.637910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8d8e0bcf82'
down_revision = '2fc9daf0bb42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('blood_group', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sub_specialization', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('years_of_experience', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('qualification', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('registration_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('practice_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('practice_address', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('initial_consultation_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('session_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('session_duration', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('session_duration')
        batch_op.drop_column('session_type')
        batch_op.drop_column('initial_consultation_fee')
        batch_op.drop_column('practice_address')
        batch_op.drop_column('practice_name')
        batch_op.drop_column('registration_number')
        batch_op.drop_column('qualification')
        batch_op.drop_column('years_of_experience')
        batch_op.drop_column('sub_specialization')
        batch_op.drop_column('blood_group')
        batch_op.drop_column('specialization')

    # ### end Alembic commands ###
