"""Add filled to task

Revision ID: 2ee94bcfcd98
Revises: d1bbda4847ff
Create Date: 2025-06-20 11:32:37.766706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ee94bcfcd98'
down_revision = 'd1bbda4847ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('task_title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('task_due_time', sa.Time(), nullable=False))
        batch_op.alter_column('task_priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='task_priority'),
               nullable=False)
        batch_op.alter_column('task_category',
               existing_type=postgresql.ENUM('consultation', 'check-up', 'follow-up', name='task_category'),
               nullable=False)
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['id'])
        batch_op.drop_column('task_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('task_category',
               existing_type=postgresql.ENUM('consultation', 'check-up', 'follow-up', name='task_category'),
               nullable=True)
        batch_op.alter_column('task_priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='task_priority'),
               nullable=True)
        batch_op.drop_column('task_due_time')
        batch_op.drop_column('task_title')
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###
