"""insert value in doctor table

Revision ID: 35c2cd7dc01b
Revises: a4083fafd2a0
Create Date: 2025-07-02 14:56:19.027400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c2cd7dc01b'
down_revision = 'a4083fafd2a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
