"""update patient model

Revision ID: 54554e185ac9
Revises: 8ebce179196f
Create Date: 2025-07-28 13:20:59.997315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54554e185ac9'
down_revision = '8ebce179196f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favourite', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('is_favourite')

    # ### end Alembic commands ###
