"""Add fields to patient

Revision ID: 5b8707c0f922
Revises: a99aa36e87a9
Create Date: 2025-06-25 16:07:09.914232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8707c0f922'
down_revision = 'a99aa36e87a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mood_scale', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mood_affect_life', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('extreme_energy', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('taking_medications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('alcohol_drug_use', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('medical_condition_mood_cause', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('medical_condition_mood_cause')
        batch_op.drop_column('alcohol_drug_use')
        batch_op.drop_column('taking_medications')
        batch_op.drop_column('extreme_energy')
        batch_op.drop_column('mood_affect_life')
        batch_op.drop_column('mood_scale')
        batch_op.drop_column('selected_category')

    # ### end Alembic commands ###
