"""Add fields to patient

Revision ID: 5d08c30808ef
Revises: cb46328965ef
Create Date: 2025-06-25 20:47:35.918778

"""
from alembic import op
import sqlalchemy as sa
from models.patient import JSONEncodedList

# revision identifiers, used by Alembic.
revision = '5d08c30808ef'
down_revision = 'cb46328965ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visited_psychiatrist', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('has_diagnosis_history', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('diagnosis_history', JSONEncodedList(), nullable=True))
        batch_op.add_column(sa.Column('is_psychiatrically_hospitalized', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_72_hour_mentally_detention_order', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('has_detained_mental_health', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('number_of_mentally_detained', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('detained_mental_health_treatment', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('has_seeking_help', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('seeking_help', sa.String(length=100), nullable=True))
        batch_op.drop_column('has_psychiatric_history')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_psychiatric_history', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('seeking_help')
        batch_op.drop_column('has_seeking_help')
        batch_op.drop_column('detained_mental_health_treatment')
        batch_op.drop_column('number_of_mentally_detained')
        batch_op.drop_column('has_detained_mental_health')
        batch_op.drop_column('is_72_hour_mentally_detention_order')
        batch_op.drop_column('is_psychiatrically_hospitalized')
        batch_op.drop_column('diagnosis_history')
        batch_op.drop_column('has_diagnosis_history')
        batch_op.drop_column('is_visited_psychiatrist')

    # ### end Alembic commands ###
