"""Add fields to patient

Revision ID: 5fadcb2116a1
Revises: 7efebba420b7
Create Date: 2025-06-25 17:01:14.760472

"""
from alembic import op
import sqlalchemy as sa
# Add this:
from models.patient import JSONEncodedList


# revision identifiers, used by Alembic.
revision = '5fadcb2116a1'
down_revision = '7efebba420b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('past_medical_history', JSONEncodedList(), nullable=True))
        batch_op.add_column(sa.Column('family_history', JSONEncodedList(), nullable=True))
        batch_op.add_column(sa.Column('medication_history', JSONEncodedList(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('medication_history')
        batch_op.drop_column('family_history')
        batch_op.drop_column('past_medical_history')

    # ### end Alembic commands ###
