"""Add fieled to patient

Revision ID: 6bbbae74c51c
Revises: c3dbf1e0a431
Create Date: 2025-06-20 17:43:56.216197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbbae74c51c'
down_revision = 'c3dbf1e0a431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
