"""Add fields to patient

Revision ID: 7efebba420b7
Revises: 5b8707c0f922
Create Date: 2025-06-25 16:35:53.981467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7efebba420b7'
down_revision = '5b8707c0f922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_past_medical_history', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_family_history', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_medication_history', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_psychiatric_history', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_personal_history', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_activities_of_daily_living', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('has_activities_of_daily_living')
        batch_op.drop_column('has_personal_history')
        batch_op.drop_column('has_psychiatric_history')
        batch_op.drop_column('has_medication_history')
        batch_op.drop_column('has_family_history')
        batch_op.drop_column('has_past_medical_history')

    # ### end Alembic commands ###
