"""Add fields to patient

Revision ID: 840010d1cddc
Revises: c5f73225230e
Create Date: 2025-06-26 10:49:28.074334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840010d1cddc'
down_revision = 'c5f73225230e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shower_ability', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shower_frequency', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dressing_ability', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('eating_ability', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('food_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('toileting_ability', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('grooming_ability', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('menstrual_management', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('household_tasks', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('daily_affairs', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('safety_mobility', sa.String(length=100), nullable=True))
        batch_op.drop_column('has_activities_of_daily_living')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_activities_of_daily_living', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('safety_mobility')
        batch_op.drop_column('daily_affairs')
        batch_op.drop_column('household_tasks')
        batch_op.drop_column('menstrual_management')
        batch_op.drop_column('grooming_ability')
        batch_op.drop_column('toileting_ability')
        batch_op.drop_column('food_type')
        batch_op.drop_column('eating_ability')
        batch_op.drop_column('dressing_ability')
        batch_op.drop_column('shower_frequency')
        batch_op.drop_column('shower_ability')

    # ### end Alembic commands ###
