"""Add fieled to patient

Revision ID: 8f1fb630f618
Revises: 6bbbae74c51c
Create Date: 2025-06-22 11:16:49.581333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1fb630f618'
down_revision = '6bbbae74c51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('height', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('blood_pressure', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('pulse', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('pulse')
        batch_op.drop_column('blood_pressure')
        batch_op.drop_column('height')
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
