"""update report

Revision ID: 93b42d9536f1
Revises: 6c10433bd8c1
Create Date: 2025-07-11 12:57:18.066833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b42d9536f1'
down_revision = '6c10433bd8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('report_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('report_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
