"""Add fields to patient

Revision ID: a99aa36e87a9
Revises: 4f1ec8241b4a
Create Date: 2025-06-24 16:45:05.127636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a99aa36e87a9'
down_revision = '4f1ec8241b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender_born_with', postgresql.ENUM('male', 'female', 'other', name='gender'), nullable=True))
        batch_op.add_column(sa.Column('gender_identified_with', postgresql.ENUM('male', 'female', 'other', name='gender'), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('kin_relation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('kin_full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('kin_contact_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gp_details', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('preferred_language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('has_physical_disabilities', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('physical_disability_specify', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('requires_wheelchair_access', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wheelchair_specify', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('needs_special_communication', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('communication_specify', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('has_hearing_impairments', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hearing_specify', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('has_visual_impairments', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('visual_specify', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('environmental_factors', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('other_accessibility_needs', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('has_health_insurance', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('insurance_provider', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('policy_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('insurance_claim_contact', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('linked_hospitals', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('additional_health_benefits', sa.String(length=200), nullable=True))
        batch_op.drop_column('gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', postgresql.ENUM('male', 'female', 'other', name='gender'), autoincrement=False, nullable=True))
        batch_op.drop_column('additional_health_benefits')
        batch_op.drop_column('linked_hospitals')
        batch_op.drop_column('insurance_claim_contact')
        batch_op.drop_column('policy_number')
        batch_op.drop_column('insurance_provider')
        batch_op.drop_column('has_health_insurance')
        batch_op.drop_column('other_accessibility_needs')
        batch_op.drop_column('environmental_factors')
        batch_op.drop_column('visual_specify')
        batch_op.drop_column('has_visual_impairments')
        batch_op.drop_column('hearing_specify')
        batch_op.drop_column('has_hearing_impairments')
        batch_op.drop_column('communication_specify')
        batch_op.drop_column('needs_special_communication')
        batch_op.drop_column('wheelchair_specify')
        batch_op.drop_column('requires_wheelchair_access')
        batch_op.drop_column('physical_disability_specify')
        batch_op.drop_column('has_physical_disabilities')
        batch_op.drop_column('preferred_language')
        batch_op.drop_column('gp_details')
        batch_op.drop_column('kin_contact_number')
        batch_op.drop_column('kin_full_name')
        batch_op.drop_column('kin_relation')
        batch_op.drop_column('contact')
        batch_op.drop_column('gender_identified_with')
        batch_op.drop_column('gender_born_with')

    # ### end Alembic commands ###
