"""add fields in patient table

Revision ID: bd297c390edf
Revises: b419d172e05d
Create Date: 2025-06-26 18:19:34.125702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd297c390edf'
down_revision = 'b419d172e05d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_physical_symptom', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mood_levels', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mood_affect_life', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('extreme_energy_periods', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reckless_spending_frequency', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_taking_medications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('alcohol_drug_use_frequency', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('medical_conditions', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('medical_conditions')
        batch_op.drop_column('alcohol_drug_use_frequency')
        batch_op.drop_column('is_taking_medications')
        batch_op.drop_column('reckless_spending_frequency')
        batch_op.drop_column('extreme_energy_periods')
        batch_op.drop_column('mood_affect_life')
        batch_op.drop_column('mood_levels')
        batch_op.drop_column('selected_physical_symptom')

    # ### end Alembic commands ###
