"""Add fields to patient

Revision ID: c5f73225230e
Revises: d7bf7d72a0cf
Create Date: 2025-06-25 23:13:11.651373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f73225230e'
down_revision = 'd7bf7d72a0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_family_mental_health_history', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('family_relationship_details', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('family_mental_health_condition', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('has_been_hospitalized_for_mental_health', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('number_of_admissions', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('outcome', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('outcome')
        batch_op.drop_column('duration')
        batch_op.drop_column('number_of_admissions')
        batch_op.drop_column('has_been_hospitalized_for_mental_health')
        batch_op.drop_column('family_mental_health_condition')
        batch_op.drop_column('family_relationship_details')
        batch_op.drop_column('has_family_mental_health_history')

    # ### end Alembic commands ###
