"""Add email to PasswordResetOTP

Revision ID: c70eed00ac4e
Revises: 27c56d0b2d75
Create Date: 2025-06-17 19:34:05.287897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70eed00ac4e'
down_revision = '27c56d0b2d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_otps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_otps', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
