"""Add fields to patient

Revision ID: cb46328965ef
Revises: 5fadcb2116a1
Create Date: 2025-06-25 19:07:15.729246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb46328965ef'
down_revision = '5fadcb2116a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_allergies', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_medication_allergatic', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('medication_allergatic', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('has_taking_medication', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('taking_medication', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('has_mental_medication', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('mental_medication', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('mental_medication')
        batch_op.drop_column('has_mental_medication')
        batch_op.drop_column('taking_medication')
        batch_op.drop_column('has_taking_medication')
        batch_op.drop_column('medication_allergatic')
        batch_op.drop_column('has_medication_allergatic')
        batch_op.drop_column('has_allergies')

    # ### end Alembic commands ###
