"""call recording model

Revision ID: d17888dd4c7c
Revises: a079f5229658
Create Date: 2025-07-08 11:26:06.356291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17888dd4c7c'
down_revision = 'a079f5229658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_records', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
