"""Add fields to patient

Revision ID: d7bf7d72a0cf
Revises: 5d08c30808ef
Create Date: 2025-06-25 22:35:01.225957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7bf7d72a0cf'
down_revision = '5d08c30808ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_planned_pregnancy', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_maternal_substance_use_during_pregnancy', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_birth_delayed', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_birth_induced', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_birth_hypoxia', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_immediate_post_natal_complications', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_require_oxygen_or_incubator', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_feed_well_as_newborn', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_sleep_well_as_newborn', sa.String(length=100), nullable=True))
        batch_op.drop_column('has_personal_history')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_personal_history', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_sleep_well_as_newborn')
        batch_op.drop_column('is_feed_well_as_newborn')
        batch_op.drop_column('is_require_oxygen_or_incubator')
        batch_op.drop_column('is_immediate_post_natal_complications')
        batch_op.drop_column('is_birth_hypoxia')
        batch_op.drop_column('is_birth_induced')
        batch_op.drop_column('is_birth_delayed')
        batch_op.drop_column('is_maternal_substance_use_during_pregnancy')
        batch_op.drop_column('is_planned_pregnancy')

    # ### end Alembic commands ###
