"""updatae fields in patient table

Revision ID: ea3b36ba6c12
Revises: 840010d1cddc
Create Date: 2025-06-26 17:12:50.788217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3b36ba6c12'
down_revision = '840010d1cddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_depressive_illness', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('depressive_frequency', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mood_level', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mood_worse_in_morning', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('mood_constantly_low', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_smile', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_laugh', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_normal_appetite_and_enjoyment', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('enjoyment_activities_description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('has_crying', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cry_frequency', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('feels_life_worth', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_suicidal_thoughts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('suicidal_frequency', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('feels_not_want_to_be_here', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('not_want_to_be_here_frequency', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('want_to_die', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('want_to_die_frequency', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('has_ending_life_thoughts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_tried_ending_life', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('life_ending_methods_details', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('has_injuries', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('injuries_description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('has_hospital_admission', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hospital_admission_details', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('has_self_harmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('self_harmed_methods', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('has_acquired_injury', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('acquired_injury_description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('has_guilt', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('guilt_reason', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('blood_vessel_damage', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('nerve_damage', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('required_stitches', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('required_surgery', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('permanent_damage_from_self_harm', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_confidence_and_self_esteem', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('self_esteem_level', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overly_happy_frequency', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('excessively_flirty', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('increased_sex_drive', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('undressed_in_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('buys_beyond_means', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('high_risk_activities', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('inflated_self_esteem', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('feels_superior', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('believes_in_powers', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('feels_wealthy_or_genius', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('anger_level', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('agitation_level', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('low_mood_duration', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('elated_mood_duration', sa.String(length=100), nullable=True))
        batch_op.drop_column('taking_medications')
        batch_op.drop_column('selected_category')
        batch_op.drop_column('mood_affect_life')
        batch_op.drop_column('mood_scale')
        batch_op.drop_column('extreme_energy')
        batch_op.drop_column('alcohol_drug_use')
        batch_op.drop_column('medical_condition_mood_cause')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_condition_mood_cause', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('alcohol_drug_use', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('extreme_energy', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mood_scale', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mood_affect_life', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('selected_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('taking_medications', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('elated_mood_duration')
        batch_op.drop_column('low_mood_duration')
        batch_op.drop_column('agitation_level')
        batch_op.drop_column('anger_level')
        batch_op.drop_column('feels_wealthy_or_genius')
        batch_op.drop_column('believes_in_powers')
        batch_op.drop_column('feels_superior')
        batch_op.drop_column('inflated_self_esteem')
        batch_op.drop_column('high_risk_activities')
        batch_op.drop_column('buys_beyond_means')
        batch_op.drop_column('undressed_in_public')
        batch_op.drop_column('increased_sex_drive')
        batch_op.drop_column('excessively_flirty')
        batch_op.drop_column('overly_happy_frequency')
        batch_op.drop_column('self_esteem_level')
        batch_op.drop_column('has_confidence_and_self_esteem')
        batch_op.drop_column('permanent_damage_from_self_harm')
        batch_op.drop_column('required_surgery')
        batch_op.drop_column('required_stitches')
        batch_op.drop_column('nerve_damage')
        batch_op.drop_column('blood_vessel_damage')
        batch_op.drop_column('guilt_reason')
        batch_op.drop_column('has_guilt')
        batch_op.drop_column('acquired_injury_description')
        batch_op.drop_column('has_acquired_injury')
        batch_op.drop_column('self_harmed_methods')
        batch_op.drop_column('has_self_harmed')
        batch_op.drop_column('hospital_admission_details')
        batch_op.drop_column('has_hospital_admission')
        batch_op.drop_column('injuries_description')
        batch_op.drop_column('has_injuries')
        batch_op.drop_column('life_ending_methods_details')
        batch_op.drop_column('has_tried_ending_life')
        batch_op.drop_column('has_ending_life_thoughts')
        batch_op.drop_column('want_to_die_frequency')
        batch_op.drop_column('want_to_die')
        batch_op.drop_column('not_want_to_be_here_frequency')
        batch_op.drop_column('feels_not_want_to_be_here')
        batch_op.drop_column('suicidal_frequency')
        batch_op.drop_column('has_suicidal_thoughts')
        batch_op.drop_column('feels_life_worth')
        batch_op.drop_column('cry_frequency')
        batch_op.drop_column('has_crying')
        batch_op.drop_column('enjoyment_activities_description')
        batch_op.drop_column('has_normal_appetite_and_enjoyment')
        batch_op.drop_column('can_laugh')
        batch_op.drop_column('can_smile')
        batch_op.drop_column('mood_constantly_low')
        batch_op.drop_column('mood_worse_in_morning')
        batch_op.drop_column('mood_level')
        batch_op.drop_column('depressive_frequency')
        batch_op.drop_column('has_depressive_illness')

    # ### end Alembic commands ###
